description "Bootstrap extended to IASD DSA Websites"

# Stylesheet importing bootstrap
# stylesheet 'styles.scss'
stylesheet 'print.scss'

image 'img/default_avatar.png', :to => 'default_avatar.png'

image 'img/global_nav/more_menu_mark.png', :to => 'global_nav/more_menu_mark.png'
image 'img/global_nav/tutorial_arrow.png', :to => 'global_nav/tutorial_arrow.png'
image 'img/global_nav/tutorial_arrow@2x.png', :to => 'global_nav/tutorial_arrow@2x.png'

image 'img/global_nav/map/region_01.png', :to => 'global_nav/map/region_01.png'
image 'img/global_nav/map/region_02.png', :to => 'global_nav/map/region_02.png'
image 'img/global_nav/map/region_03.png', :to => 'global_nav/map/region_03.png'
image 'img/global_nav/map/region_04.png', :to => 'global_nav/map/region_04.png'
image 'img/global_nav/map/region_05.png', :to => 'global_nav/map/region_05.png'
image 'img/global_nav/map/region_06.png', :to => 'global_nav/map/region_06.png'
image 'img/global_nav/map/region_07.png', :to => 'global_nav/map/region_07.png'
image 'img/global_nav/map/region_08.png', :to => 'global_nav/map/region_08.png'
image 'img/global_nav/map/region_09.png', :to => 'global_nav/map/region_09.png'
image 'img/global_nav/map/region_10.png', :to => 'global_nav/map/region_10.png'
image 'img/global_nav/map/region_11.png', :to => 'global_nav/map/region_11.png'
image 'img/global_nav/map/region_12.png', :to => 'global_nav/map/region_12.png'
image 'img/global_nav/map/region_13.png', :to => 'global_nav/map/region_13.png'
image 'img/global_nav/map/region_14.png', :to => 'global_nav/map/region_14.png'
image 'img/global_nav/map/region_15.png', :to => 'global_nav/map/region_15.png'
image 'img/global_nav/map/region_16.png', :to => 'global_nav/map/region_16.png'
image 'img/global_nav/map/region_17.png', :to => 'global_nav/map/region_17.png'

image 'img/headers/institutional.png', :to => 'headers/institutional.png'
image 'img/headers/destaque-pedidos-de-oracao.png', :to => 'headers/destaque-pedidos-de-oracao.png'

image 'img/institutional/download-badge.png', :to => 'institutional/download-badge.png'
image 'img/institutional/div.png', :to => 'institutional/div.png'
image 'img/institutional/sprite_bandeiras.svg', :to => 'institutional/sprite_bandeiras.svg'
image 'img/institutional/sprite_icones.svg', :to => 'institutional/sprite_icones.svg'
image 'img/institutional/video-play.png', :to => 'institutional/video-play.png'

image 'img/logos_pt_BR/iasd_header.png', :to => 'logos_pt_BR/iasd_header.png'
image 'img/logos_pt_BR/iasd_header@2x.png', :to => 'logos_pt_BR/iasd_header@2x.png'
image 'img/logos_pt_BR/iasd_dsa_home.png', :to => 'logos_pt_BR/iasd_dsa_home.png'
image 'img/logos_pt_BR/iasd_dsa_home@2x.png', :to => 'logos_pt_BR/iasd_dsa_home@2x.png'
image 'img/logos_pt_BR/iasd_footer.png', :to => 'logos_pt_BR/iasd_footer.png'
image 'img/logos_pt_BR/iasd_footer@2x.png', :to => 'logos_pt_BR/iasd_footer@2x.png'
image 'img/logos_pt_BR/iasd_header_vertical.png', :to => 'logos_pt_BR/iasd_header_vertical.png'
image 'img/logos_pt_BR/iasd_header_vertical@2x.png', :to => 'logos_pt_BR/iasd_header_vertical@2x.png'
image 'img/logos_pt_BR/iasd_header_symbol.png', :to => 'logos_pt_BR/iasd_header_symbol.png'
image 'img/logos_pt_BR/iasd_header_symbol@2x.png', :to => 'logos_pt_BR/iasd_header_symbol@2x.png'
image 'img/logos_pt_BR/iasd_404.png', :to => 'logos_pt_BR/iasd_404.png'
image 'img/logos_pt_BR/iasd_404@2x.png', :to => 'logos_pt_BR/iasd_404@2x.png'

image 'img/logos_es_ES/iasd_header.png', :to => 'logos_es_ES/iasd_header.png'
image 'img/logos_es_ES/iasd_header@2x.png', :to => 'logos_es_ES/iasd_header@2x.png'
image 'img/logos_es_ES/iasd_dsa_home.png', :to => 'logos_es_ES/iasd_dsa_home.png'
image 'img/logos_es_ES/iasd_dsa_home@2x.png', :to => 'logos_es_ES/iasd_dsa_home@2x.png'
image 'img/logos_es_ES/iasd_footer.png', :to => 'logos_es_ES/iasd_footer.png'
image 'img/logos_es_ES/iasd_footer@2x.png', :to => 'logos_es_ES/iasd_footer@2x.png'
image 'img/logos_es_ES/iasd_header_vertical.png', :to => 'logos_es_ES/iasd_header_vertical.png'
image 'img/logos_es_ES/iasd_header_vertical@2x.png', :to => 'logos_es_ES/iasd_header_vertical@2x.png'
image 'img/logos_es_ES/iasd_header_symbol.png', :to => 'logos_es_ES/iasd_header_symbol.png'
image 'img/logos_es_ES/iasd_header_symbol@2x.png', :to => 'logos_es_ES/iasd_header_symbol@2x.png'
image 'img/logos_es_ES/iasd_404.png', :to => 'logos_es_ES/iasd_404.png'
image 'img/logos_es_ES/iasd_404@2x.png', :to => 'logos_es_ES/iasd_404@2x.png'

image 'img/widgets/gallery_frame.png', :to => 'widgets/gallery_frame.png'
image 'img/widgets/gallery_frame@2x.png', :to => 'widgets/gallery_frame@2x.png'
image 'img/widgets/reticle.png', :to => 'widgets/reticle.png'
image 'img/widgets/slider_full.png', :to => 'widgets/slider_full.png'
image 'img/widgets/background_find_church.png', :to => 'widgets/background_find_church.png'
image 'img/widgets/title_novo_tempo.png', :to => 'widgets/title_novo_tempo.png'
image 'img/widgets/new_issue.png', :to => 'widgets/new_issue.png'
image 'img/widgets/new_issue@2x.png', :to => 'widgets/new_issue@2x.png'
image 'img/widgets/no_image_40x40.png', :to => 'widgets/no_image_40x40.png'
image 'img/widgets/no_image_70x45.png', :to => 'widgets/no_image_70x45.png'
image 'img/widgets/no_image_124x124.png', :to => 'widgets/no_image_124x124.png'
image 'img/widgets/no_image_132x85.png', :to => 'widgets/no_image_132x85.png'
image 'img/widgets/no_image_140x90.png', :to => 'widgets/no_image_140x90.png'
image 'img/widgets/no_image_145x190.png', :to => 'widgets/no_image_145x190.png'
image 'img/widgets/no_image_150x100.png', :to => 'widgets/no_image_150x100.png'
image 'img/widgets/no_image_180x235.png', :to => 'widgets/no_image_180x235.png'
image 'img/widgets/no_image_220x220.png', :to => 'widgets/no_image_220x220.png'
image 'img/widgets/no_image_290x186.png', :to => 'widgets/no_image_290x186.png'
image 'img/widgets/no_image_290x220.png', :to => 'widgets/no_image_290x220.png'
image 'img/widgets/no_image_293x185.png', :to => 'widgets/no_image_293x185.png'
image 'img/widgets/no_image_345x218.png', :to => 'widgets/no_image_345x218.png'
image 'img/widgets/no_image_400x260.png', :to => 'widgets/no_image_400x260.png'
image 'img/widgets/no_image_400x400.png', :to => 'widgets/no_image_400x400.png'
image 'img/widgets/no_image_460x200.png', :to => 'widgets/no_image_460x200.png'
image 'img/widgets/no_image_617x220.png', :to => 'widgets/no_image_617x220.png'
image 'img/widgets/no_image_617x460.png', :to => 'widgets/no_image_617x460.png'
image 'img/widgets/no_image_720x300.png', :to => 'widgets/no_image_720x300.png'
image 'img/widgets/no_image_720x350.png', :to => 'widgets/no_image_720x350.png'
image 'img/widgets/no_image_740x475.png', :to => 'widgets/no_image_740x475.png'
image 'img/widgets/no_image_940x415.png', :to => 'widgets/no_image_940x415.png'
image 'img/widgets/no_image_1920x600.png', :to => 'widgets/no_image_1920x600.png'
image 'img/widgets/loader.gif', :to => 'widgets/loader.gif'

image 'img/plugins/loader.gif', :to => 'plugins/loader.gif'

image 'img/favicons/favicon.ico', :to => 'favicons/favicon.ico'
image 'img/favicons/apple-touch-icon-57x57.png', :to => 'favicons/apple-touch-icon-57x57.png'
image 'img/favicons/apple-touch-icon-114x114.png', :to => 'favicons/apple-touch-icon-114x114.png'
image 'img/favicons/apple-touch-icon-72x72.png', :to => 'favicons/apple-touch-icon-72x72.png'
image 'img/favicons/apple-touch-icon-144x144.png', :to => 'favicons/apple-touch-icon-144x144.png'
image 'img/favicons/apple-touch-icon-60x60.png', :to => 'favicons/apple-touch-icon-60x60.png'
image 'img/favicons/apple-touch-icon-120x120.png', :to => 'favicons/apple-touch-icon-120x120.png'
image 'img/favicons/apple-touch-icon-76x76.png', :to => 'favicons/apple-touch-icon-76x76.png'
image 'img/favicons/apple-touch-icon-152x152.png', :to => 'favicons/apple-touch-icon-152x152.png'
image 'img/favicons/favicon-196x196.png', :to => 'favicons/favicon-196x196.png'
image 'img/favicons/favicon-160x160.png', :to => 'favicons/favicon-160x160.png'
image 'img/favicons/favicon-96x96.png', :to => 'favicons/favicon-96x96.png'
image 'img/favicons/favicon-32x32.png', :to => 'favicons/favicon-32x32.png'
image 'img/favicons/favicon-16x16.png', :to => 'favicons/favicon-16x16.png'
image 'img/favicons/mstile-144x144.png', :to => 'favicons/mstile-144x144.png'
image 'img/favicons/mstile-70x70.png', :to => 'favicons/mstile-70x70.png'
image 'img/favicons/mstile-144x144.png', :to => 'favicons/mstile-144x144.png'
image 'img/favicons/mstile-150x150.png', :to => 'favicons/mstile-150x150.png'
image 'img/favicons/mstile-310x310.png', :to => 'favicons/mstile-310x310.png'
image 'img/favicons/mstile-310x150.png', :to => 'favicons/mstile-310x150.png'


font 'fonts/futurastd-book-webfont.eot', :to => 'futurastd-book-webfont.eot'  
font 'fonts/futurastd-book-webfont.svg', :to => 'futurastd-book-webfont.svg'  
font 'fonts/futurastd-book-webfont.ttf', :to => 'futurastd-book-webfont.ttf'  
font 'fonts/futurastd-book-webfont.woff', :to => 'futurastd-book-webfont.woff' 
font 'fonts/futurastd-light-webfont.eot', :to => 'futurastd-light-webfont.eot' 
font 'fonts/futurastd-light-webfont.svg', :to => 'futurastd-light-webfont.svg' 
font 'fonts/futurastd-light-webfont.ttf', :to => 'futurastd-light-webfont.ttf' 
font 'fonts/futurastd-light-webfont.woff', :to => 'futurastd-light-webfont.woff'
font 'fonts/futurastd-medium-webfont.eot', :to => 'futurastd-medium-webfont.eot' 
font 'fonts/futurastd-medium-webfont.svg', :to => 'futurastd-medium-webfont.svg' 
font 'fonts/futurastd-medium-webfont.ttf', :to => 'futurastd-medium-webfont.ttf' 
font 'fonts/futurastd-medium-webfont.woff', :to => 'futurastd-medium-webfont.woff'

# javascript 'lib/bootstrap.min.js', :to => 'bootstrap.min.js'
# javascript 'lib/respond.min.js', :to => 'respond.min.js'
# javascript 'lib/html5shiv.js', :to => 'html5shiv.js'
# javascript 'lib/modernizr.js', :to => 'modernizr.js'
# javascript 'lib/owl.carousel.js', :to => 'owl.carousel.js'
# javascript 'lib/masonry.pkgd.min.js', :to => 'masonry.pkgd.min.js'
# javascript 'lib/mediaelement-and-player.min.js', :to => 'mediaelement-and-player.min.js'
# javascript 'lib/iasd_global_nav.js', :to => 'iasd_global_nav.js'
# javascript 'lib/iasd_main_nav.js', :to => 'iasd_main_nav.js'
# javascript 'lib/iasd_dropdown_nav.js', :to => 'iasd_dropdown_nav.js'
# javascript 'lib/iasd_footer.js', :to => 'iasd_footer.js'
# javascript 'lib/iasd_widgets.js', :to => 'iasd_widgets.js'
# javascript 'lib/iasd_plugins.js', :to => 'iasd_plugins.js'
# javascript 'lib/iasd_home_dsa.js', :to => 'iasd_home_dsa.js'

javascript 'lib/iasd-bootstrap.js', :to => 'iasd-bootstrap.js'
javascript 'lib/iasd-bootstrap.min.js', :to => 'iasd-bootstrap.min.js'
javascript 'lib/ltie9.js', :to => 'ltie9.js'
javascript 'lib/ltie9.min.js', :to => 'ltie9.min.js'

# Javascripts
#%w(affix alert button carousel collapse dropdown modal popover scrollspy tab tooltip transition typeahead).each do |file|
#  javascript "#{basedir}/javascripts/bootstrap-#{file}.js", :to => "bootstrap-#{file}.js"
#end